# Generated by Django 3.2.20 on 2023-07-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=6),
            preserve_default=False,
        ),
    ]
