# Generated by Django 3.2.20 on 2023-07-30 21:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_savedproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedProducts',
            new_name='SavedItem',
        ),
    ]
