# Generated by Django 3.2.20 on 2023-07-31 17:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_rename_saveditems_savedproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedproducts',
            old_name='saved_product',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='savedproducts',
            unique_together={('user', 'product')},
        ),
    ]
